language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -d -v ./...
  - go get github.com/stretchr/testify/assert
  - go install -v ./...

notifications:
  email: false

script:
  - go vet ./...
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled